🚀 Major Enhancements to Voice Notes Sync
mysticcoders/voicenotes-sync pull request #35
Opened 2024-08-04 11:24 UTC by hjamet

# 🚀 Major Enhancements to Voice Notes Sync

This pull request addresses the following issues:
- 🔗 https://github.com/mysticcoders/voicenotes-sync/issues/34
- 🔗 https://github.com/mysticcoders/voicenotes-sync/issues/32
- 🔗 https://github.com/mysticcoders/voicenotes-sync/issues/31
- 🔗 https://github.com/mysticcoders/voicenotes-sync/issues/30

## 🦦 List of Added Changes

### 1. 📁 Sub-notes Support
- Sub-notes are now synchronized and listed in a subsection of the parent note's "Related Notes" section.

### 2. 🎨 Custom Instructions Support
- Custom instructions created by templates are added to the note in a "Custom" section.

### 3. 🧹 Tidy Transcript
- Tidy transcripts are now added normally to notes.
- A new option (default: True) has been added to replace original transcripts with their tidy version if available.

### 4. 📊 Summary and Key Points Prioritization
- If available, the note's summary and/or key points are displayed first, before the transcript, for easier reading.

### 5. ⏱️ Note Duration and Timestamp Correction
- Note properties are now in a more human-readable format.

## 💖 Thank You Note

From the bottom of my heart, thank you for this amazing plugin! I hope this contribution will bring joy to everyone! 🍡

2024-08-05 10:41 UTC, yshhwy commented
Thank you for your contribution to the project! I tested the code, and all functionalities work as expected. The improvements are excellent and greatly enhance the project. Your efforts in addressing the issues and improving the code are greatly appreciated. Your hard work and dedication help make this project better for everyone. Looking forward to more of your valuable contributions in the future!

2024-08-08 23:55 UTC, kinabalu requested changes
can you merge from latest main, i've added eslint and prettier as a lot of the "updates" here are only cosmetic so makes it hard to read the PR for actual changes.

Also what I've been thinking about is for the processing of a "note" to be put into an object, and the building of the template itself to be a configurable setting with a sensible default in place that can always be reverted to. I'd like this a bit more I think

Might help with the tidy option that I don't see in the UI? What am I missing?

2024-08-09 13:46 UTC, hjamet commented
I'll take care of any conflicts :)
As for the Tidy option, it replaces the original transcript with its "cleaned" version if generated :)

2024-08-09 16:19 UTC, hjamet commented
- ✅ **Merged with the latest main branch** 🔄
- 🖌️ **Implementation of improvements:**
  - Integration of Jinja formatting for notes 📝
  - Update of date formats 📅
- 🐛 **Fixes:**
  - Resolution of typing issues 🧮
  - Package version updates 📦
- 🆕 **Additions:**
  - Inclusion of all missing fields to the Jinja template (creations, related and joined notes, tags and attachments) 🧩

2024-08-09 16:39 UTC, kinabalu requested changes
getting closer -- lets clean up and make the changes and perhaps we can get a group of folks to help test the changes before we push.

my thought is we'll deploy this as a beta using BRAT and if we don't get any bugs out of it, push it live.

thank you for the code!

2024-08-09 16:39 UTC, kinabalu commented on types.ts
> +  data: any[]; // Le type exact des éléments du tableau dépendra de la structure de vos enregistrements
can we remove the comments here or write them in english?

2024-08-09 16:39 UTC, kinabalu commented on main.ts
> +    noteTemplate: `# {{ title }}\n\nDate: {{ date }}\n{% if summary %}## Summary\n\n{{ summary }}{% endif %}\n{% if points %}## Main points\n\n{{ points }}{% endif %}\n{% if attachments %}## Attachme
lets make this a multiline string so its easier to read and edit later

2024-08-09 16:39 UTC, kinabalu commented on settings.ts
> +          .setPlaceholder('# {{ title }}\n\nDate: {{ date }}\n{% if summary %}## Summary\n\n{{ summary }}{% endif %}\n{% if points %}## Main points\n\n{{ points }}{% endif %}\n{% if attachments %}##
lets just refer again to the noteTemplate here rather than duplicate the text.

2024-08-09 16:39 UTC, kinabalu commented on main.ts
> +    duration: ${Math.floor(recording.duration / 60000) > 0
let's not do inline calculations like this, prefer externalizing into a function

2024-08-09 16:39 UTC, kinabalu commented on main.ts
> +    ${recording.tags && recording.tags.length > 0 ? `tags: ${recording.tags.map((tag: { name: string }) => tag.name).join(',')}` : ''}
same here, externalized this to a function

2024-08-09 17:24 UTC, hjamet commented
Thank you from the bottom of my heart! 🦦 
I've just made the changes 🙃

2024-08-09 17:36 UTC, kinabalu approved these changes

2024-08-14 02:15 UTC, merged

2024-08-14 06:50 UTC, giittyy commented
Great work! This is an awesome update. It seems to be pulling dates correctly base on local timezone for the title/document portion. Can we please also have this for the created_at and updated_at properties?

2024-08-15 21:22 UTC, hjamet commented
Thank you! I'll check it out if I have a moment ;)